### ISSUE TITLE
Emergency pdf that is sent out weekly

### ISSUE THREAD

**Issue by raubreywhite** [folkehelseinstituttet/dashboards_sykdomspuls#79]
Look here and see the CONFIG: https://github.com/folkehelseinstituttet/dashboards_sykdomspuls/blob/master/R/aaGlobalVariables.R

CONFIG$SYNDROMES is the brains of the system. It contains the information about which analyses will be run. The last 5 tags are "emerg1", "emerg2", "emerg3", "emerg4", "emerg5". These are the tags that will be used during an emergency.

The syndromes that define "emerg*" are defined inside the sikkersone aggregation code, so you don't have to worry about that. The main point is that every week, 5 emergency codes are provided in our analysis dataset, and when an emergency happens the diagnoses behind these emergency codes will actually correspond to something useful.

"AnalyseEmerg" is the function that renders https://github.com/folkehelseinstituttet/dashboards_sykdomspuls/blob/master/inst/extdata/emerg.Rmd into a pdf that is distributed weekly to the sykdomspulsen team (but when an emergency happens we will open up the distribution list to the relevant people).

We need https://github.com/folkehelseinstituttet/dashboards_sykdomspuls/blob/master/inst/extdata/emerg.Rmd to actually contain something useful. The aim is to provide a template that can be quickly adapted to an emergency and deployed within 24 hours.

**Comment by Gulfa** [comment]
@raubreywhite and @GryMGr: I have started to look at this issue and I have some questions. 

1. In what type of emergency are we expecting to use this analysis? Are we thinking about a situation like an influenza pandemic or we considering a situation when we start receiving information about a new symptom? Maybe both of these situations are important?
2. Are we assuming that we already have a declared emergency that we need to monitor or is there still some element of outbreak detection that is important here?
3. In an emergency situation are we still looking at daily aggregated data on a municipality level or would we need more individual-level data and knowledge of which facility the doctor is reporting from?
4. Do we know anything about the date of onset of symptoms or are we always operating with the date of the consultation?
5. In outbreak situations, one often is interested in both probable and confirmed cases, do we need some way of including or interfacing with other systems that can provide this data?

**Comment by GryMGr** [comment]
Great that you have started to look at this! :)
1: It could be both. I think an influenza pandemic is the most probable right now, but you never know. Also, there will be an emergency exercise in the autumn, so we should have something ready to test out.

2: It will be sent out if we have a decleared emergency. But we allso need it now for the group working on scabies. They do want to have some overview of gender that they do not have in the dashboard.

3: It could be both depending on the emergency situation. Most probable we are interested in some small counties that we need to assign when the emergency start, then when the emergency is getting bigger we might need to scale up to county level.

4: We must use the date of the consultation, unfortunately we can not get any data about the onset of symptomes.

5: It would be very good to link his system with MSIS, VESUV and other databases, but for now we can only use Sykdomspulsen. I really want to have some dialogue about this in the autumn to see what we can do.

I guess these were a bit vague answers, sorry for that. Just send me an  e-mail or ask more questions here if you want. We can also talk more about this in our skype meeting on Tuesday.

**Comment by raubreywhite** [comment]
Suggestion: age is displayed as (demographic) population pyramid. One for the start of the outbreak (first week?). One for entire period? Instead of multiple epicurves per age group

**Comment by Gulfa** [comment]
I think that could be a reasonable idea. At least a demographic pyramid for the whole outbreak could be very nice. Have no very strong preferences for epi-curves by age group vs multiple demographic pyramides.
