### ISSUE TITLE
Include MeM in the weekly run

### ISSUE THREAD

**Issue by raubreywhite** [folkehelseinstituttet/dashboards_sykdomspuls#90]
Gry needs to explain what is needed.

**Comment by GryMGr** [comment]
Moving Epidemic Method (MEM) is used for the tresholds that gives the start of an influenza season, the intensity and the end of the season. This should be implemented in the internal dashboard for the influenza surveillance. Since the MEM threshold calculation only work if there is seasonality in the data, it should only be implemented on Norway and County Level. Further analysis is needed before inclusion on the municipality level.

**Comment by raubreywhite** [comment]
Extra info:

MEM R package: https://cran.r-project.org/web/packages/mem/index.html

Step 1:
Programatically create the folder `results/sykdomspuls/mem`

Step 2:
Produce Figure 2 in 
[2019-20-influensaovervaking-2018-2019-uke-20.pdf](https://github.com/folkehelseinstituttet/dashboards_sykdomspuls/files/3276575/2019-20-influensaovervaking-2018-2019-uke-20.pdf) (taken from https://www.fhi.no/publ/2018/influensasesongen-i-norge-2018-2019-ukerapporter/) for Norway and all fylke, and save them into `results/sykdomspuls/mem` as `.png` files

Step 3:
Implement it in the internal dashboard as @GryMGr said

**Comment by raubreywhite** [comment]
Also it would be great to make the maps at the end of the .pdf ("Kart med andel influensalignende sykdom") and also put them in the `results/sykdomspuls/mem` folder. You should use https://folkehelseinstituttet.github.io/fhidata/articles/Datasets.html#county-maps-norway_map_counties

**Comment by raubreywhite** [comment]
I wonder if it would make more sense to have a `results/sykdomspuls/influensa` folder, so we can have specific syndromes?

**Comment by raubreywhite** [comment]
The advice from the communications dept is to use palette "map_seq_complete"  https://folkehelseinstituttet.github.io/fhiplot/articles/palettes.html

**Comment by GryMGr** [comment]
The pandemic season (2009/2010) should be excluded before calculating MEM.

**Comment by raubreywhite** [comment]
It also only runs between weeks 40 and 20 (I think?). So if it is between weeks 21 and 39, then you should just produce graphs as if it were week 20.

So if the last date of data in the system is from week...

2018-19: produce graphs as if it were 2018-19
2018-20: produce graphs as if it were 2018-20
2018-21: produce graphs as if it were 2018-20
2018-22: produce graphs as if it were 2018-20
...
2018-39: produce graphs as if it were 2018-20
2018-40: produce graphs as if it were 2018-40
2018-41: produce graphs as if it were 2018-41
